-
  branches:
    only:
    - nuget

  image: Visual Studio 2019

  before_build:
    - dotnet restore Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln

  build_script: 
    - dotnet build Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - dotnet pack -c Release "Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.csproj" /p:NuspecFile="Ghpr.SpecFlow.nuspec"

  artifacts:
    - path: '**\*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory
        
-
  branches:
    only:
    - nuget-common

  image: Visual Studio 2019

  before_build:
    - dotnet restore Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln

  build_script: 
    - dotnet build Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - dotnet pack -c Release "Ghpr.SpecFlowPlugin/Ghpr.SpecFlow.Common/GhprSpecFlow.Common.csproj" /p:NuspecFile="GhprSpecFlow.Common.nuspec"

  artifacts:
    - path: '**\*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
 
  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory

-
  branches:
    only:
    - nuget-nunit

  image: Visual Studio 2019

  before_build:
    - dotnet restore Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln

  build_script: 
    - dotnet build Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - dotnet pack -c Release "Ghpr.SpecFlowPlugin/Ghpr.NUnit.SpecFlowPlugin/GhprNUnit.SpecFlowPlugin.csproj" /p:NuspecFile="GhprNUnit.SpecFlowPlugin.nuspec"

  artifacts:
    - path: '**\*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory

-
  branches:
    only:
    - nuget-mstest

  image: Visual Studio 2019

  before_build:
    - dotnet restore Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln

  build_script: 
    - dotnet build Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - dotnet pack -c Release "Ghpr.SpecFlowPlugin/GhprMSTest.SpecFlowPlugin/GhprMSTest.SpecFlowPlugin.csproj" /p:NuspecFile="GhprMSTest.SpecFlowPlugin.nuspec"

  artifacts:
    - path: '**\*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
 
  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory        

-
  branches:
    only:
    - master

  image: Visual Studio 2019

  before_build:
    - dotnet restore Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln

  build_script: 
    - dotnet build Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln /p:Configuration=Release /t:Rebuild

  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory
