-
  branches:
    only:
    - nuget
    
  before_build:
    - nuget restore Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln

  build_script: 
    - msbuild Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln /p:Configuration=Release /t:Rebuild

  after_build:
    - nuget pack "Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.csproj" -Prop Configuration=Release

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
 
  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory
        
-
  branches:
    except:
    - nuget
    
  before_build:
    - nuget restore Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln

  build_script: 
    - msbuild Ghpr.SpecFlowPlugin/Ghpr.SpecFlowPlugin.sln /p:Configuration=Release /t:Rebuild

  test:
    assemblies:
      - '**\*TestsExample.dll'
      - '**\*TestsExample2.dll'
    categories:
      only:
        - SuccessCategory
